[package]
name = "circles-rs"
version = "0.1.0"
authors = ["Doimhneacht <hanna.rosul@gmail.com>"]

[dependencies]

gfx = "^0.16"
gfx_app = "^0.5"
glutin = "^0.8"
gfx_window_glutin = "^0.16"
rand = "^0.3"
